# Generated by Django 3.0.5 on 2020-11-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('bloodgroup', models.TextField()),
                ('date_pos', models.TextField()),
                ('date_neg', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('city', models.TextField()),
                ('exist_cond', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('bloodgroup', models.TextField()),
                ('hospital', models.TextField()),
                ('amt_needed', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('city', models.TextField()),
                ('exist_cond', models.TextField()),
            ],
        ),
    ]
